version: '3'
services:
  php-fpm:
    build: ./docker/php-fpm
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: sample_app_dev
      DB_USER: app
      DB_PASS: pass
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - socket:/var/run/php-fpm:consistent
      - ./src:/var/www:cached
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini:cached
      - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - socket:/var/run/php-fpm:consistent
      - ./src:/var/www:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:cached
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:cached
      - ./docker_volumes/mysql/data:/var/lib/mysql:delegated
      - ./docker_volumes/mysql/log:/var/log/mysql:delegated
  redis:
    build: ./docker/redis
    ports:
      - "6379:6379"
  sftp:
    image: atmoz/sftp:alpine
    volumes:
      - ./docker_volumes/sftp/upload:/home/laravel/upload:delegated
    ports:
      - "22:22"
    command: laravel:pass:1001
volumes:
  socket:
